spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # для разработки: create, create-drop или update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
